#!/bin/bash

echo "Инициализация не требуется"
echo "Структура проекта:"
echo "backend/"
echo "│"
echo "├── app/"
echo "│   ├── __init__.py"
echo "│   ├── app.py              # Основной файл приложения"
echo "│   ├── routes/             # Роутеры"
echo "│   │   ├── __init__.py"
echo "│   │   └── api.py         # Эндпоинты API"
echo "│   ├── models/             # Модели данных"
echo "│   │   ├── __init__.py"
echo "│   │   └── schemas.py     # Схемы данных"
echo "│   ├── config.py           # Конфигурация"
echo "│   └── extensions.py       # Расширения (например, БД)"
echo "│"
echo "├── requirements.txt        # Зависимости Python"
echo "└── Dockerfile              # Docker конфигурация"
