#!/bin/bash

echo "Инициализация не требуется"
echo "Структура проекта:"
echo "backend/"
echo "│"
echo "├── app/"
echo "│   ├── __init__.py"
echo "│   ├── main.py              # Основной файл приложения"
echo "│   ├── api/                 # Роутеры API"
echo "│   │   ├── __init__.py"
echo "│   │   ├── endpoints.py     # Эндпоинты"
echo "│   ├── models/              # Модели данных (Pydantic/SQLAlchemy)"
echo "│   │   ├── __init__.py"
echo "│   │   ├── schemas.py       # Pydantic схемы"
echo "│   ├── database/            # Работа с БД"
echo "│   │   ├── __init__.py"
echo "│   │   └── connection.py    # Подключение к БД"
echo "│   └── config.py            # Конфигурация приложения"
echo "│"
echo "├── requirements.txt         # Зависимости Python"
echo "└── Dockerfile               # Docker конфигурация"
