#!/bin/bash

echo "Инициализация не требуется"
echo "Структура проекта (Rust):"
echo "backend/"
echo "│"
echo "├── src/"
echo "│   ├── main.rs            # Точка входа"
echo "│   ├── routes/           # Модули маршрутов"
echo "│   │   ├── mod.rs        # Публичный API модуля"
echo "│   │   └── items.rs      # Эндпоинты для /items"
echo "│   ├── models/           # Модели данных"
echo "│   │   ├── mod.rs"
echo "│   │   └── item.rs       # Структуры Item"
echo "│   ├── errors.rs         # Кастомные ошибки"
echo "│   └── app_state.rs      # Состояние приложения"
echo "│"
echo "├── Cargo.toml            # Зависимости Rust"
echo "├── Dockerfile            # Docker конфигурация"
echo "└── .env                  # Переменные окружения"
