name: Live Demo

on:
  workflow_dispatch
#  push:
#    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: compose
      run: docker compose up --build
